import "../styles/style.css";
const cookies = [
  {
    name: "Gingerbrave",
    skill: "charge",
    rarity: "common",
    usefulIn: ["arena", "master mode", "odyssey"],
  },

  {
    name: "Cotton Cookie",
    skill: "support",
    rarity: "epic",
    usefulIn: ["arena", "world exploration", "master mode", "odyssey"],
  },
  {
    name: "Financier Cookie",
    skill: "defense",
    rarity: "epic",
    usefulIn: ["arena", "master mode", "odyssey"],
  },
  {
    name: "Caramel Arrow Cookie",
    skill: "ranged",
    rarity: "epic",
    usefulIn: ["arena", "world exploration", "master mode", "odyssey"],
  },
  {
    name: "Black Pearl Cookie",
    skill: "ambush",
    rarity: "legendary",
    usefulIn: ["arena", "world exploration", "master mode"],
  },
  {
    name: "",
    skill: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "",
    skill: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "",
    skill: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "",
    skill: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "",
    skill: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "",
    skill: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "",
    skill: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "",
    skill: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "",
    skill: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "",
    skill: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "",
    skill: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "",
    skill: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "",
    skill: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "",
    skill: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "",
    skill: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "",
    skill: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "",
    skill: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "",
    skill: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "",
    skill: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "",
    skill: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "",
    skill: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "",
    skill: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "",
    skill: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "",
    skill: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "",
    skill: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "",
    skill: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "",
    skill: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "",
    skill: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "",
    skill: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "",
    skill: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "",
    skill: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "",
    skill: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "",
    skill: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "",
    skill: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "",
    skill: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "",
    skill: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "",
    skill: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "",
    skill: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "",
    skill: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "",
    skill: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "",
    skill: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "",
    skill: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "",
    skill: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "",
    skill: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "",
    skill: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "",
    skill: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "",
    skill: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "",
    skill: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "",
    skill: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "",
    skill: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "",
    skill: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "",
    skill: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "",
    skill: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "",
    skill: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "",
    skill: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "",
    skill: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "",
    skill: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "",
    skill: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "",
    skill: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "",
    skill: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "",
    skill: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "",
    skill: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "",
    skill: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "",
    skill: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "",
    skill: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "",
    skill: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "",
    skill: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "",
    skill: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "",
    skill: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "",
    skill: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "",
    skill: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "",
    skill: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "",
    skill: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "",
    skill: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "",
    skill: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "",
    skill: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "",
    skill: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "",
    skill: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "angel cookie",
    skill: "healer",
    rarity: "common",
    usefulIn: ["", "", ""],
  },
  {
    name: "ninja cookie",
    skill: "ambush",
    rarity: "common",
    usefulIn: ["arena", "world exploration"],
  },
];
