import "../styles/style.css";

const cookies = [
  {
    name: "Gingerbrave",
    type: "charge",
    rarity: "common",
    usefulIn: ["arena", "master mode", "odyssey"],
  },

  {
    name: "Cotton Cookie",
    type: "support",
    rarity: "epic",
    usefulIn: ["arena", "world exploration", "master mode", "odyssey"],
  },
  {
    name: "Financier Cookie",
    type: "defense",
    rarity: "epic",
    usefulIn: ["arena", "master mode", "odyssey"],
  },
  {
    name: "Caramel Arrow Cookie",
    type: "ranged",
    rarity: "epic",
    usefulIn: ["arena", "world exploration", "master mode", "odyssey"],
  },
  {
    name: "Black Pearl Cookie",
    type: "ambush",
    rarity: "legendary",
    usefulIn: ["arena", "world exploration", "master mode"],
  },
  {
    name: "",
    type: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "",
    type: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "",
    type: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "",
    type: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "",
    type: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "",
    type: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "",
    type: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "",
    type: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "",
    type: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "cream puff cookie",
    type: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "eclair cookie",
    type: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "caramel arrow cookie",
    type: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "twizzly gummy cookie",
    type: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "purple yam cookie",
    type: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "wildberry cookie",
    type: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "financier cookie",
    type: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "chili pepper cookie",
    type: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "espresso cookie",
    type: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "affogato cookie",
    type: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "pumpkin pie cookie",
    type: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "crunchy chip cookie",
    type: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "cream unicorn cookie",
    type: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "pomegranate cookie",
    type: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "dark choco cookie",
    type: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "cherry blossom cookie",
    type: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "licorice cookie",
    type: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "strawberry crepe cookie",
    type: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "",
    type: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "rye cookie",
    type: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "black raisin cookie",
    type: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "raspberry cookie",
    type: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "",
    type: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "herb cookie",
    type: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "pastry cookie",
    type: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "almond cookie",
    type: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "werewolf cookie",
    type: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "squid ink cookie",
    type: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "tiger lily cookie",
    type: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "cocoa cookie",
    type: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "latte cookie",
    type: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "moon rabbit cookie",
    type: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "lilac cookie",
    type: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "milk cookie",
    type: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "madeleine cookie",
    type: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "snow sugar cookie",
    type: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "tea knight cookie",
    type: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "mint choco cookie",
    type: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "mango cookie",
    type: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "fig cookie",
    type: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "kumiho cookie",
    type: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "mushroom cookie",
    type: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "sparkling cookie",
    type: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "black caviar cookie",
    type: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "schwarzwalder",
    type: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "parfait cookie",
    type: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "red velvet cookie",
    type: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "macaron cookie",
    type: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "candy diver cookie",
    type: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "carol cookie",
    type: "",
    rarity: "",
    usefulIn: ["", "", ""],
  },
  {
    name: "bts cookie",
    type: "bts",
    rarity: "special",
    usefulIn: ["arena", "world exploration", "tosc", "all"],
  },
  {
    name: "tails cookie",
    type: "ambush",
    rarity: "special",
    usefulIn: ["decor", "arena"],
  },
  {
    name: "sonic cookie",
    type: "ambush",
    rarity: "special",
    usefulIn: ["decor", "arena"],
  },
  {
    name: "cherry cookie",
    type: "bomber",
    rarity: "rare",
    usefulIn: ["tosc", "arena", "world exploration"],
  },
  {
    name: "carrot cookie",
    type: "support",
    rarity: "rare",
    usefulIn: ["arena"],
  },
  {
    name: "adventurer cookie",
    type: "ambush",
    rarity: "rare",
    usefulIn: ["world exploration"],
  },
  {
    name: "blackberry cookie",
    type: "magic",
    rarity: "rare",
    usefulIn: ["guild battle", "world exploration", "arena"],
  },
  {
    name: "avocado cookie",
    type: "defense",
    rarity: "rare",
    usefulIn: ["arena", "world exploration"],
  },
  {
    name: "pancake cookie",
    type: "ambush",
    rarity: "rare",
    usefulIn: ["arena", "tosc"],
  },
  {
    name: "onion cookie",
    type: "support",
    rarity: "rare",
    usefulIn: ["arena", "world exploration"],
  },
  {
    name: "devil cookie",
    type: "magic",
    rarity: "rare",
    usefulIn: ["tosc"],
  },
  {
    name: "clover cookie",
    type: "support",
    rarity: "rear",
    usefulIn: ["arena", "tosc"],
  },
  {
    name: "gumball cookie",
    type: "bomber",
    rarity: "rare",
    usefulIn: ["tosc", "arena", "world exploration"],
  },
  {
    name: "princess cookie",
    type: "charge",
    rarity: "rare",
    usefulIn: ["world exploration", "guild battle", "arena"],
  },
  {
    name: "custard cookie iii",
    type: "healing",
    rarity: "rare",
    usefulIn: ["arena", "world exploration", "odyssey"],
  },
  {
    name: "muscle cookie",
    type: "charge",
    rarity: "super-ultra-extra-rare",
    usefulIn: ["beauty contest"],
  },
  {
    name: "wizard cookie",
    type: "magic",
    rarity: "common",
    usefulIn: ["world exploration", "guild battle"],
  },
  {
    name: "strawberry cookie",
    type: "defense",
    rarity: "common",
    usefulIn: ["world exploration"],
  },
  {
    name: "beet cookie",
    type: "ranged",
    rarity: "common",
    usefulIn: ["arena", "world exploration"],
  },
  {
    name: "angel cookie",
    type: "healer",
    rarity: "common",
    usefulIn: ["arena", "world exploration"],
  },
  {
    name: "ninja cookie",
    type: "ambush",
    rarity: "common",
    usefulIn: ["arena", "world exploration"],
  },
];
